---
# tasks file for user
- name: Ensure 'wheel' group exists
  group:
    name: wheel
    state: present

- name: Add new user
  user:
    name: "{{ user }}"
    groups: wheel

# Based on https://stackoverflow.com/questions/33359404/ansible-best-practice-for-maintaining-list-of-sudoers
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -csf %s'
